### ISSUE TITLE
Create interactive instruction dialog

### ISSUE THREAD

**Issue by k105la** [akilhylton/pulsebox-js#10]
### Summary
Make an interactive walk through that displays step by step instructions on how to us pulsebox properly.

### Resources
https://getbootstrap.com/docs/4.0/components/modal/

**Comment by Tatiana-Smith** [comment]
I would love to help you with this project.

**Comment by k105la** [comment]
Your contribution would be definitely be appreciated however this project is deprectated please refer to [pulsetracker](https://github.com/akilhylton/pulsetracker/tree/ui) this is where the new version of this project has been moved.
